name: Deploy Infrastructure

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: Terraform Apply
    runs-on: ubuntu-latest
    env:
      TF_CLOUD_TOKEN: ${{ secrets.TF_CLOUD_TOKEN }}

    defaults:
      run:
        working-directory: /home/runner/work/freqtrade-bot/freqtrade-bot/infra

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.6

      - name: Configure Terraform credentials
        run: |
          mkdir -p ~/.terraform.d
          cat > ~/.terraform.d/credentials.tfrc.json <<EOF
          {
            "credentials": {
              "app.terraform.io": {
                "token": "${{ secrets.TF_CLOUD_TOKEN }}"
              }
            }
          }
          EOF

      - name: Terraform Init
        run: terraform init
        env:
          TF_VAR_hcloud_token: ${{ secrets.HCLOUD_TOKEN }}
          TF_VAR_client_ip: ${{ secrets.CLIENT_IP }}
          TF_VAR_ssh_key_name: ${{ secrets.SSH_KEY_NAME }}
          TF_CLOUD_TOKEN: ${{ secrets.TF_CLOUD_TOKEN }}

      - name: Terraform Validate
        run: terraform validate
        env:
          TF_VAR_hcloud_token: ${{ secrets.HCLOUD_TOKEN }}
          TF_VAR_client_ip: ${{ secrets.CLIENT_IP }}
          TF_VAR_ssh_key_name: ${{ secrets.SSH_KEY_NAME }}
          TF_CLOUD_TOKEN: ${{ secrets.TF_CLOUD_TOKEN }}

      - name: Terraform Plan
        run: terraform plan -input=false
        env:
          TF_VAR_hcloud_token: ${{ secrets.HCLOUD_TOKEN }}
          TF_VAR_client_ip: ${{ secrets.CLIENT_IP }}
          TF_VAR_ssh_key_name: ${{ secrets.SSH_KEY_NAME }}
          TF_CLOUD_TOKEN: ${{ secrets.TF_CLOUD_TOKEN }}

      - name: Terraform Apply
        run: terraform apply -auto-approve
        env:
          TF_VAR_hcloud_token: ${{ secrets.HCLOUD_TOKEN }}
          TF_VAR_client_ip: ${{ secrets.CLIENT_IP }}
          TF_VAR_ssh_key_name: ${{ secrets.SSH_KEY_NAME }}
          TF_CLOUD_TOKEN: ${{ secrets.TF_CLOUD_TOKEN }}
