name: Destroy Infrastructure

on:
  workflow_dispatch:

jobs:
  terraform:
    name: Terraform Destroy
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: /home/runner/work/freqtrade-bot/freqtrade-bot/infra

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      - name: Terraform Init
        run: terraform init
        env:
          TF_VAR_hcloud_token: ${{ secrets.HCLOUD_TOKEN }}
          TF_VAR_client_ip: ${{ secrets.CLIENT_IP }}
          TF_VAR_ssh_key_name: ${{ secrets.SSH_KEY_NAME }}

      - name: Terraform Destroy
        run: terraform destroy -auto-approve
        env:
          TF_VAR_hcloud_token: ${{ secrets.HCLOUD_TOKEN }}
          TF_VAR_client_ip: ${{ secrets.CLIENT_IP }}
          TF_VAR_ssh_key_name: ${{ secrets.SSH_KEY_NAME }}
