name: Terraform Cloud Token Test

on:
  workflow_dispatch:

jobs:
  validate-token:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.6

      - name: Configure Terraform credentials
        run: |
          mkdir -p ~/.terraform.d
          cat > ~/.terraform.d/credentials.tfrc.json <<EOF
          {
            "credentials": {
              "app.terraform.io": {
                "token": "${{ secrets.TF_CLOUD_TOKEN }}"
              }
            }
          }
          EOF

      - name: Create minimal Terraform config
        run: |
          cat > main.tf <<EOF
          terraform {
            cloud {
              organization = "freqcap"

              workspaces {
                name = "freqtrade-infra"
              }
            }
          }
          EOF

      - name: Terraform Init (tests token)
        run: terraform init
