name: Terraform Cloud Token Test

on:
  workflow_dispatch:

jobs:
  validate-token:
    runs-on: ubuntu-latest
    env:
      TF_CLOUD_TOKEN: ${{ secrets.TF_CLOUD_TOKEN }}
      hostname: app.terraform.io

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      - name: Configure backend (create dummy main.tf)
        run: |
          echo '
          terraform {
            cloud {
              organization = "freqcap"

              workspaces {
                name = "freqtrade-infra"
              }
            }
          }
          ' > main.tf

      - name: Terraform Init (validates TF_CLOUD_TOKEN)
        run: terraform init
